//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSFussionCompanie.WSCompanies {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FusionCompaniesService_FusionCompaniesTrigger_REQUEST_binding", Namespace="http://xmlns.mx.com.televisa/OIC/Utility")]
    public partial class FusionCompanies : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFusionCompaniesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FusionCompanies() {
            this.Url = global::WSFussionCompanie.Properties.Settings.Default.WSFussionCompanie_WSCompanies_FusionCompanies;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFusionCompaniesCompletedEventHandler GetFusionCompaniesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetFusionCompanies", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFusionCompaniesRspMsg", Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
        public GetFusionCompaniesRspMsgType GetFusionCompanies([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")] GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg) {
            object[] results = this.Invoke("GetFusionCompanies", new object[] {
                        GetFusionCompaniesReqMsg});
            return ((GetFusionCompaniesRspMsgType)(results[0]));
        }
        
        /// <remarks/>
        public void GetFusionCompaniesAsync(GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg) {
            this.GetFusionCompaniesAsync(GetFusionCompaniesReqMsg, null);
        }
        
        /// <remarks/>
        public void GetFusionCompaniesAsync(GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg, object userState) {
            if ((this.GetFusionCompaniesOperationCompleted == null)) {
                this.GetFusionCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFusionCompaniesOperationCompleted);
            }
            this.InvokeAsync("GetFusionCompanies", new object[] {
                        GetFusionCompaniesReqMsg}, this.GetFusionCompaniesOperationCompleted, userState);
        }
        
        private void OnGetFusionCompaniesOperationCompleted(object arg) {
            if ((this.GetFusionCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFusionCompaniesCompleted(this, new GetFusionCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class GetFusionCompaniesReqMsgType {
        
        private string inputField;
        
        /// <remarks/>
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class CompanyType {
        
        private string businessUnitIdField;
        
        private string businessUnitNameField;
        
        private string orgIDField;
        
        private string legalEntityIdentifierField;
        
        /// <remarks/>
        public string BusinessUnitId {
            get {
                return this.businessUnitIdField;
            }
            set {
                this.businessUnitIdField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessUnitName {
            get {
                return this.businessUnitNameField;
            }
            set {
                this.businessUnitNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrgID {
            get {
                return this.orgIDField;
            }
            set {
                this.orgIDField = value;
            }
        }
        
        /// <remarks/>
        public string LegalEntityIdentifier {
            get {
                return this.legalEntityIdentifierField;
            }
            set {
                this.legalEntityIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class GetFusionCompaniesRspMsgType {
        
        private CompanyType[] companiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Company", IsNullable=false)]
        public CompanyType[] Companies {
            get {
                return this.companiesField;
            }
            set {
                this.companiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFusionCompaniesCompletedEventHandler(object sender, GetFusionCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFusionCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFusionCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFusionCompaniesRspMsgType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFusionCompaniesRspMsgType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591