//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraxtorWS.servicieCompanies {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.mx.com.televisa/OIC/Utility", ConfigurationName="servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST")]
    public interface FusionCompaniesService_FusionCompaniesTrigger_REQUEST {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetFusionCompanies no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="GetFusionCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse GetFusionCompanies(ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetFusionCompanies", ReplyAction="*")]
        System.Threading.Tasks.Task<ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse> GetFusionCompaniesAsync(ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class GetFusionCompaniesReqMsgType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("Input");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class CompanyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessUnitIdField;
        
        private string businessUnitNameField;
        
        private string orgIDField;
        
        private string legalEntityIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BusinessUnitId {
            get {
                return this.businessUnitIdField;
            }
            set {
                this.businessUnitIdField = value;
                this.RaisePropertyChanged("BusinessUnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessUnitName {
            get {
                return this.businessUnitNameField;
            }
            set {
                this.businessUnitNameField = value;
                this.RaisePropertyChanged("BusinessUnitName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrgID {
            get {
                return this.orgIDField;
            }
            set {
                this.orgIDField = value;
                this.RaisePropertyChanged("OrgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LegalEntityIdentifier {
            get {
                return this.legalEntityIdentifierField;
            }
            set {
                this.legalEntityIdentifierField = value;
                this.RaisePropertyChanged("LegalEntityIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1")]
    public partial class GetFusionCompaniesRspMsgType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompanyType[] companiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Company", IsNullable=false)]
        public CompanyType[] Companies {
            get {
                return this.companiesField;
            }
            set {
                this.companiesField = value;
                this.RaisePropertyChanged("Companies");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFusionCompaniesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1", Order=0)]
        public ExtraxtorWS.servicieCompanies.GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg;
        
        public GetFusionCompaniesRequest() {
        }
        
        public GetFusionCompaniesRequest(ExtraxtorWS.servicieCompanies.GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg) {
            this.GetFusionCompaniesReqMsg = GetFusionCompaniesReqMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFusionCompaniesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xlmns.mx.com.televisa/UtilService/Core/FusionCompanies/V1", Order=0)]
        public ExtraxtorWS.servicieCompanies.GetFusionCompaniesRspMsgType GetFusionCompaniesRspMsg;
        
        public GetFusionCompaniesResponse() {
        }
        
        public GetFusionCompaniesResponse(ExtraxtorWS.servicieCompanies.GetFusionCompaniesRspMsgType GetFusionCompaniesRspMsg) {
            this.GetFusionCompaniesRspMsg = GetFusionCompaniesRspMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FusionCompaniesService_FusionCompaniesTrigger_REQUESTChannel : ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient : System.ServiceModel.ClientBase<ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST>, ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST {
        
        public FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient() {
        }
        
        public FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FusionCompaniesService_FusionCompaniesTrigger_REQUESTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST.GetFusionCompanies(ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest request) {
            return base.Channel.GetFusionCompanies(request);
        }
        
        public ExtraxtorWS.servicieCompanies.GetFusionCompaniesRspMsgType GetFusionCompanies(ExtraxtorWS.servicieCompanies.GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg) {
            ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest inValue = new ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest();
            inValue.GetFusionCompaniesReqMsg = GetFusionCompaniesReqMsg;
            ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse retVal = ((ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST)(this)).GetFusionCompanies(inValue);
            return retVal.GetFusionCompaniesRspMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse> ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST.GetFusionCompaniesAsync(ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest request) {
            return base.Channel.GetFusionCompaniesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExtraxtorWS.servicieCompanies.GetFusionCompaniesResponse> GetFusionCompaniesAsync(ExtraxtorWS.servicieCompanies.GetFusionCompaniesReqMsgType GetFusionCompaniesReqMsg) {
            ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest inValue = new ExtraxtorWS.servicieCompanies.GetFusionCompaniesRequest();
            inValue.GetFusionCompaniesReqMsg = GetFusionCompaniesReqMsg;
            return ((ExtraxtorWS.servicieCompanies.FusionCompaniesService_FusionCompaniesTrigger_REQUEST)(this)).GetFusionCompaniesAsync(inValue);
        }
    }
}
